import { HttpClient } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { map, take, tap } from 'rxjs/operators';
import { environment } from 'src/environments/environment';

@Injectable({
	providedIn: 'root'
})
export class DashboardApiService {
	constructor(private http: HttpClient) {}

	getFormCount() {
		return this.http
			.get<FormsCountRes>(`${environment.apiUrl}dashboard/getCount`)
			.pipe(map((res) => res.data[0]));
	}
}

// Generated by https://quicktype.io

export interface FormsCountRes {
	status: string;
	code: number;
	data: FormsCount[];
}

export interface FormsCount {
	hazardResult: number;
	incidentFormResult: number;
	riskAssessmentResult: number;
	toolBoxResult: number;
	siteInspectionResult: number;
	savedDynamicFormResult: number;
	nearMissCount: number;
	firstAidCount: number;
	medicalTreatmentCount: number;
	lostTimeInjuryCount: number;
	deathDataCount: number;
}
