// Generated by https://quicktype.io

export interface JurisDictionResponce {
	status: string;
	code: number;
	data: JurisDictionData[];
}

export interface JurisDictionData {
	index: number;
	status: string;
	_id: string;
	title: string;
	createdAt: Date;
	updatedAt: Date;
	__v: number;
}
