// Generated by https://quicktype.io

export interface RegulatorResponce {
	status: string;
	code: number;
	data: RegulatorData[];
}

export interface RegulatorData {
	index: number;
	status: string;
	_id: string;
	title: string;
	createdAt: Date;
	updatedAt: Date;
	__v: number;
}
